pub mod error;
pub mod domain;
pub mod traits;
pub mod actor;
mod deepwork;
mod bruteforce_coder;
pub mod deep_research;
mod testers;
pub mod yardmaster;
mod devops;
mod ui;
mod red_team;
pub mod juniors;
mod ralph;

pub use actor::{AgentActor, ActorHandle, ActorMessage, ActorState, Supervisor, SharedSupervisor, new_shared_supervisor};
pub use deepwork::DeepworkLoop;
pub use bruteforce_coder::BruteforceCoderLoop;
pub use deep_research::DeepResearchLoop;
pub use testers::TestersLoop;
pub use yardmaster::{YardmasterLoop, SlicingStrategy, E2ESlice, ExecutionMode, TaskDecomposition, SliceGraph};
pub use devops::DevopsLoop;
pub use ui::UiLoop;
pub use red_team::RedTeamLoop;
pub use juniors::JuniorsLoop;
pub use ralph::RalphLoop;
pub use error::{LoopError, Result};
pub use domain::{MotivationSummary, RewardSummary, MotivationTier};
pub use traits::{Loop, LoopInput, LoopOutput, LoopStats};
