pub mod traits;
mod deepwork;
mod bruteforce_coder;
mod deep_research;
mod testers;
mod yardmaster;
mod devops;
mod ui;
mod red_team;
mod juniors;
mod ralph;

pub use traits::{Loop, LoopInput, LoopOutput, LoopStats, LoopError, Result};
pub use deepwork::DeepworkLoop;
pub use bruteforce_coder::BruteforceCoderLoop;
pub use deep_research::DeepResearchLoop;
pub use testers::TestersLoop;
pub use yardmaster::YardmasterLoop;
pub use devops::DevopsLoop;
pub use ui::UiLoop;
pub use red_team::RedTeamLoop;
pub use juniors::JuniorsLoop;
pub use ralph::RalphLoop;
